default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: awesomeapp_development
 
test:
  <<: *default
  database: awesomeapp_test
 
production:
  <<: *default
  database: awesomeapp_production
  username: awesomeapp
  password: <%= ENV['AWESOMEAPP_DATABASE_PASSWORD'] %>
